const REPORT_STATUS = {
  TODO: 'TODO',
  INPROGRESS: 'INPROGRESS',
  SUBMITTED: 'SUBMITTED',
  DONE: 'DONE',
};

const TYPE_TASK = {
  NEW: 'NEW',
  ENHANCE: 'ENHANCE',
};

const USER_TASK_QUERY = {
  ALL: 'ALL',
  CREATOR: 'CREATOR',
  ASSIGNEE: 'ASSIGNEE',
};

const LOG_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE',
};

module.exports = {
  REPORT_STATUS,
  TYPE_TASK,
  USER_TASK_QUERY,
  LOG_ACTIONS,
};
